import React, { useState } from "react";
import { obfuscateEmail } from "../Utils/helpers"; // Adjust path as necessary

const FAQsSection = props => {
  const [openIndex, setOpenIndex] = useState(null);

  const { email: supportEmail, mailto: supportMailto } = obfuscateEmail("support", "autoblogger.bot");

  const faqs = [
    {
      question: "What is autoBlogger?",
      answer: "autoBlogger is a fully automated blog creation tool that uses AI to generate SEO-friendly content for your Shopify (and limited Wix) store."
    },
    {
      question: "How does the 14-day free trial work?",
      answer: "You can start a 14-day free trial with no obligation. After the trial, you can continue on a paid plan or cancel at any time."
    },
    {
      question: "How long does it take to set up autoBlogger?",
      answer: "Setup typically takes just a few minutes. After that, generation and publishing can run automatically on your chosen schedule."
    },
    {
      question: "How many articles can I expect each week?",
      answer: "Depending on your plan, you can choose 1, 3, or 7 articles per week."
    },
    {
      question: "What kind of content does autoBlogger create?",
      answer: "High-quality, SEO-optimised blog posts including clean HTML, sensible metadata, and on-page SEO elements."
    },
    {
      question: "What AI model does autoBlogger use?",
      answer: "We use cutting-edge AI models and upgrade them over time. The exact model may change as newer, better options become available."
    },
    {
      question: "Can I customise the articles generated by autoBlogger?",
      answer: "Yes. You can edit drafts or published posts directly in Shopify’s blog interface, or adjust settings in autoBlogger."
    },
    {
      question: "What is the Backlink Programme (Premium)?",
      answer:
        "The Backlink Programme is available on paid plans. When you opt in, your store can be featured in other users’ spotlight articles and vice versa, helping build high-quality backlinks and visibility."
    },
    {
      question: "Is autoBlogger available in multiple languages?",
      answer: (
        <>
          Yes. Support varies by language. See the{" "}
          <a href="https://apps.shopify.com/autoblogger" target="_blank" rel="noopener noreferrer" className="text-primary underline">
            app listing
          </a>{" "}
          for the latest list.
        </>
      )
    },
    {
      question: "What platforms is autoBlogger currently available on?",
      answer: "autoBlogger is available on Shopify, and with limited features on Wix."
    },
    {
      question: "How do I install and set up autoBlogger?",
      answer: (
        <>
          Install from the{" "}
          <a href="https://apps.shopify.com/autoblogger" target="_blank" rel="noopener noreferrer" className="text-primary underline">
            Shopify App Store
          </a>
          , then follow the in-app guided setup.
        </>
      )
    },
    {
      question: "How does autoBlogger ensure the quality of the generated content?",
      answer: "We combine strong prompts, guardrails, and automated checks with the option for you to review and edit before (or after) publishing."
    },
    {
      question: "Can I cancel my subscription at any time?",
      answer: "Yes. Shopify manages billing and subscriptions, and you can cancel at any time according to their policies."
    },
    {
      question: "Weekly Spotlight Articles (Premium)",
      answer: (
        <>
          Paid plans include automatic entry into our weekly draw for a Medium spotlight article featuring your store. If selected, we’ll email you the link—add{" "}
          <a href={supportMailto} className="text-primary underline">
            {supportEmail}
          </a>{" "}
          to your safe senders. If you’re not happy with the piece, just let us know and we’ll remove it.
        </>
      )
    },
    {
      question: "How do I contact support?",
      answer: (
        <>
          Email Ollie (developer & owner) at{" "}
          <a href={supportMailto} className="text-primary underline">
            {supportEmail}
          </a>
          .
        </>
      )
    },
    {
      question: "I have ideas to improve the app; who can I contact?",
      answer: (
        <>
          I’d love to hear them. Please email{" "}
          <a href={supportMailto} className="text-primary underline">
            {supportEmail}
          </a>
          .
        </>
      )
    },
    {
      question: "What is the pricing for autoBlogger after the free trial?",
      answer: (
        <>
          We offer plans for 1, 3, or 7 blogs per week, with monthly and annual options. See current pricing on the{" "}
          <a href="https://apps.shopify.com/autoblogger" target="_blank" rel="noopener noreferrer" className="text-primary underline">
            app listing
          </a>
          .
        </>
      )
    },
    {
      question: "How does autoBlogger handle my data and privacy?",
      answer: "We take data security seriously and follow platform guidelines to protect your information."
    },
    {
      question: "What is SEO?",
      answer: "Search Engine Optimisation (SEO) is the practice of improving your site’s visibility in search results so customers can find you more easily."
    },
    {
      question: "How can blogs help with SEO?",
      answer: "Regular, relevant posts increase topical authority, keyword coverage, and the potential for backlinks—signals search engines value."
    },
    {
      question: "What other strategies can I use to improve SEO?",
      answer: "Alongside blogging, focus on technical SEO (site speed, structure, mobile), on-page optimisation, quality backlinks, and helpful product/page content."
    }
  ];

  const toggleFAQ = index => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section className="py-16 md:bg-gradient-to-b md:from-white md:to-gray-100">
      {props.home ? (
        <h3 className="text-3xl font-bold text-center mb-8 text-gray-800">Frequently Asked Questions about autoBlogger</h3>
      ) : (
        <h1 className="text-3xl font-bold text-center mb-8 text-gray-800">Frequently Asked Questions about autoBlogger</h1>
      )}

      <div className="max-w-3xl mx-auto">
        <p className="text-lg text-gray-700 mb-6">Find answers to your most common questions below:</p>

        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <div key={index} className="bg-white rounded shadow">
              <button
                className="flex justify-between items-center w-full p-4 text-left text-lg font-semibold text-gray-800 bg-gray-200 rounded hover:bg-gray-300 transition"
                onClick={() => toggleFAQ(index)}
                aria-expanded={openIndex === index}
                aria-controls={`faq-panel-${index}`}
              >
                {faq.question}
                <span aria-hidden="true">{openIndex === index ? "−" : "+"}</span>
              </button>

              {openIndex === index && (
                <div id={`faq-panel-${index}`} className="p-4 border-t border-gray-200">
                  {typeof faq.answer === "string" ? <p className="text-gray-700">{faq.answer}</p> : <div className="text-gray-700">{faq.answer}</div>}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default FAQsSection;
